<script>
    console.log("BubbleChart", "BubbleChart");

    import {GoogleCharts} from 'google-charts';
    export let stockName;

    GoogleCharts.load(drawChart);

    function bollinger(arr, index, size) {
        if(index-size < 0) {
            return NaN;
        }
        
        const numArray =  arr.slice(index-size, index);

        const mean = numArray.reduce((s, n) => s + n) / numArray.length;
        const variance = numArray.reduce((s, n) => s + (n - mean) ** 2, 0) / (numArray.length - 1);
        const stddev = Math.sqrt(variance);
        
        return {
            high: mean + 2 * stddev,
            low: mean - 2 * stddev,
        }
    }


    function donchian(arr, index, size) {
        if(index-size < 0) {
            return NaN;
        }

        const numArray =  arr.slice(index-size, index);

        return {
            high: numArray.reduce((a,b) => {return a > b ? a : b}), 
            low: numArray.reduce((a,b) => {return a < b ? a : b})
        };
    }

    function sma(arr, index, size) {
        if(index-size < 0) {
            return NaN;
        }

        return arr.slice(index-size, index).reduce((a,v,i)=>(a*i+v)/(i+1));
   }

   export const stocks = ["%5EOMX",
"AAK.ST",
"FASTAT.ST",
"ABB.ST",
/*
"ABLI.ST",
"ACAD.ST",
"ACQ-SPAC.ST",
"ATIC.ST",
"ACTI.ST",
"ALIF-B.ST",
"ANOD-B.ST",
"ADDT-B.ST",
"AOI.ST",
"AFRY.ST",
"ALFA.ST",
"APAC-SPAC-A.ST",
"ALIG.ST",
"ATORX.ST",
"ALLIGO-B.ST",
"AMBEA.ST",
"ANNE-B.ST",
"ANOT.ST",
"AQ.ST",
"ARP.ST",
"ARION-SDB.ST",
"ARISE.ST",
"ARJO-B.ST",
"ARPL.ST",
"ACE.ST",
"ASSA-B.ST",
"AZN.ST",
"ATCO-A.ST",
"ATCO-B.ST",
"ATRLJ-B.ST",
"ATT.ST",
"ATVEXA-B.ST",
"ALIV-SDB.ST",
"AZA.ST",
"AXFO.ST",
"B3.ST",
"BACTI-B.ST",
"BALCO.ST",
"BEGR.ST",
"BEIA-B.ST",
"BELE.ST",
"BEIJ-B.ST",
"BERG-B.ST",
"BRG-B.ST",
"BESQ.ST",
"BETS-B.ST",
"BETCO.ST",
"BHG.ST",
"BICO.ST",
"BILI-A.ST",
"BILL.ST",
"BIOA-B.ST",
"BIOG-B.ST",
"BINV.ST",
"BIOT.ST",
"BORG.ST",
"BOL.ST",
"BONAV-A.ST",
"BONAV-B.ST",
"BONEX.ST",
"BONG.ST",
"BOOZT.ST",
"BOUL.ST",
"BRAV.ST",
"BRIN-B.ST",
"BTS-B.ST",
"BUFAB.ST",
"BULTEN.ST",
"BURE.ST",
"BFG.ST",
"BMAX.ST",
"CALTX.ST",
"CAMX.ST",
"CANTA.ST",
"CARY.ST",
"CAST.ST",
//"CAT-A.ST",
"CAT-B.ST",
"CATE.ST",
"CTM.ST",
"CCC.ST",
"CEVI.ST",
"CBTT-B.ST",
"CIBUS.ST",
"CINT.ST",
"CLAS-B.ST",
"CLA-B.ST",
"COLL.ST",
"CNCJO-B.ST",
"COIC.ST",
"CCOR-B.ST",
"COOR.ST",
"CORE-PREF.ST",
"CORE-A.ST",
"CORE-B.ST",
"CORE-D.ST",
"CRAD-B.ST",
"CRED-A.ST",
"CPAC-SPAC.ST",
"CTEK.ST",
"CTT.ST",
"DEDI.ST",
"DIOS.ST",
"DOM.ST",
"DORO.ST",
"DUNI.ST",
"DURC-B.ST",
"DUST.ST",
"EAST.ST",
"EGTX.ST",
"ELAN-B.ST",
"ELEC.ST",
"EPRO-B.ST",
"ELUX-A.ST",
"ELUX-B.ST",
"EKTA-B.ST",
"ELOS-B.ST",
"ELTEL.ST",
"EMPIR-B.ST",
"ENDO.ST",
"ENEA.ST",
"ENRO.ST",
"ENRO-PREF-A.ST",
"ENRO-PREF-B.ST",
"ENQ.ST",
"EOLU-B.ST",
"EPI-A.ST",
"EPI-B.ST",
"EPIS-B.ST",
"EQT.ST",
"ERIC-A.ST",
"ERIC-B.ST",
"ESSITY-A.ST",
"ESSITY-B.ST",
//"ETX.ST",
"EVO.ST",
"EWRK.ST",
"FABG.ST",
"FAG.ST",
"FG.ST",
"BALD-B.ST",
"TRIAN-B.ST",
"FPAR-PREF.ST",
"FPAR-A.ST",
"FPAR-D.ST",
"FOI-B.ST",
"FNM.ST",
"FING-B.ST",
"FMM-B.ST",
"FPIP.ST",
"G5EN.ST",
"GIGSEK.ST",
"GARO.ST",
"GPG.ST",
"GETI-B.ST",
"GHP.ST",
"GRNG.ST",
"GREEN.ST",
"HLDX.ST",
"HNSA.ST",
"HANZA.ST",
"HAV-B.ST",
"HEBA-B.ST",
"HEM.ST",
"HM-B.ST",
"HEXA-B.ST",
"HTRO.ST",
"HPOL-B.ST",
"HMS.ST",
"HOFI.ST",
"HOLM-A.ST",
"HOLM-B.ST",
"HUFV-A.ST",
"HUM.ST",
"HUSQ-A.ST",
"HUSQ-B.ST",
"IAR-B.ST",
"ICA.ST",
"IS.ST",
"IMMU.ST",
"IMMNOV.ST",
"INDU-A.ST",
"INDU-C.ST",
"INDT.ST",
"IBT-B.ST",
"INFREA.ST",
"INSTAL.ST",
"IPCO.ST",
"INTRUM.ST",
"INVE-A.ST",
"INVE-B.ST",
"IVSO.ST",
"INWI.ST",
"IRLAB-A.ST",
"IRRAS.ST",
"ISOFOL.ST",
"ITAB.ST",
"JM.ST",
"JOMA.ST",
"JOSE.ST",
"K2A-PREF.ST",
"K2A-B.ST",
"KABE-B.ST",
"KAR.ST",
"KARO.ST",
"KDEV.ST",
"KFAST-B.ST",
"KIND-SDB.ST",
"KINV-A.ST",
"KINV-B.ST",
"KLARA-B.ST",
"KNOW.ST",
"LAGR-B.ST",
"LAMM-B.ST",
"LATO-B.ST",
"LEO.ST",
"LIFCO-B.ST",
"LIME.ST",
"LINC.ST",
"LIAB.ST",
"LOGI-A.ST",
"LOGI-B.ST",
"LOOMIS.ST",
"LUC.ST",
"LUND-B.ST",
"LUNE.ST",
"LUG.ST",
"LUMI.ST",
"MAHA-A.ST",
"MEAB-B.ST",
"MCAP.ST",
"MCOV-B.ST",
"MVIR-B.ST",
"MEKO.ST",
"MSAB-B.ST",
"MSON-A.ST",
"MSON-B.ST",
"MIDW-A.ST",
"MIDW-B.ST",
"MILDEF.ST",
"TIGO-SDB.ST",
"MIPS.ST",
"MOB.ST",
"MTG-A.ST",
"MTG-B.ST",
"MOMENT.ST",
"MULQ.ST",
"MTRS.ST",
"MYCR.ST",
"NAXS.ST",
"NCAB.ST",
"NCC-A.ST",
"NCC-B.ST",
"NMAN.ST",
"NELLY.ST",
"NETI-B.ST",
"NETEL.ST",
"NEWA-B.ST",
"NGS.ST",
"NIBE-B.ST",
"NIL-B.ST",
"NIVI-B.ST",
"NOBI.ST",
"NOBINA.ST",
"NOLA-B.ST",
"NDA-SE.ST",
"NENT-A.ST",
"NENT-B.ST",
"NPAPER.ST",
"NWG.ST",
"NORB-B.ST",
"SAVE.ST",
"NORVA.ST",
"NOTE.ST",
"NTEK-B.ST",
"NP3.ST",
"NP3-PREF.ST",
"NYF.ST",
"OASM.ST",
"OEM-B.ST",
"ONCO.ST",
"ORES.ST",
"ORX.ST",
"ORTI-A.ST",
"ORTI-B.ST",
"OP.ST",
"OP-PREF.ST",
"OP-PREFB.ST",
"OVZON.ST",
"PNDX-B.ST",
"PEAB-B.ST",
"PIERCE.ST",
"PLAZ-B.ST",
"POOL-B.ST",
"PREC.ST",
"PREV-B.ST",
"PRIC-B.ST",
"PACT.ST",
"PROB.ST",
"PROF-B.ST",
"PRFO.ST",
"PENG-B.ST",
"QLINEA.ST",
"QLIRO.ST",
"RAIL.ST",
"RATO-A.ST",
"RATO-B.ST",
"RAY-B.ST",
"READ.ST",
"REJL-B.ST",
"RESURS.ST",
"RIZZO-B.ST",
"RROS.ST",
"RVRC.ST",
"SAAB-B.ST",
"SAGA-A.ST",
"SAGA-B.ST",
"SAGA-D.ST",
"SBB-B.ST",
"SBB-D.ST",
"SAND.ST",
"SANION.ST",
"SAS.ST",
"SCST.ST",
"SHOT.ST",
"SDIP-PREF.ST",
"SDIP-B.ST",
"SECT-B.ST",
"SECU-B.ST",
"SEMC.ST",
"SENS.ST",
"SEZI.ST",
"SRNKE-B.ST",
"SINCH.ST",
"SINT.ST",
"SIVE.ST",
"SEB-A.ST",
"SEB-C.ST",
"SKA-B.ST",
"SKF-A.ST",
"SKF-B.ST",
"SKIS-B.ST",
"SLEEP.ST",
"SOF-B.ST",
"SFAB.ST",
"SSAB-A.ST",
"SSAB-B.ST",
"STAR-A.ST",
"STAR-B.ST",
"STEF-B.ST",
"SF.ST",
"STWK.ST",
"STE-A.ST",
"STE-R.ST",
"STOR-B.ST",
"STRAX.ST",
"SVIK.ST",
"SVED-B.ST",
"SCA-A.ST",
"SCA-B.ST",
"SHB-A.ST",
"SHB-B.ST",
"SVOL-A.ST",
"SVOL-B.ST",
"SWEC-A.ST",
"SWEC-B.ST",
"SWED-A.ST",
"SWMA.ST",
"SOBI.ST",
"SYNSAM.ST",
"SYSR.ST",
"TBD30-SPAC-A.ST",
"TEL2-A.ST",
"TEL2-B.ST",
"TELIA.ST",
"TETY.ST",
"TFBANK.ST",
"THULE.ST",
"TIETOS.ST",
"TOBII.ST",
"TDVOX.ST",
"TRAC-B.ST",
"TRAD.ST",
"TRANS.ST",
"8TRA.ST",
"TREL-B.ST",
"TROAX.ST",
"TRUE-B.ST",
"VBG-B.ST",
"VNE-SDB.ST",
"VICO.ST",
"VSSAB-B.ST",
"VIT-B.ST",
"VITR.ST",
"VNV.ST",
"VOLO.ST",
"VOLO-PREF.ST",
"VOLCAR-B.ST",
"VOLV-A.ST",
"VOLV-B.ST",
"WALL-B.ST",
"WBGR-B.ST",
"WIHL.ST",
"WISE.ST",
"XANO-B.ST",
"XBRANE.ST",
"XSPRAY.ST",
"XVIVO.ST",
*/
];


    function drawChart() {
        var chart = new google.visualization.BubbleChart(document.getElementById('chart_div'));
        var options = {
           title: 'Bubble',
            width: 1600,
            height: 800,
            hAxis: {title: 'MACD'},
            vAxis: {title: 'Squeeze'},
        };

        var data = google.visualization.arrayToDataTable([], true);
        data.addColumn("string", "stock");
        data.addColumn("number", "macd");
        data.addColumn("number", "squeeze");
        //data.addColumn("string", "category");
        //data.addColumn("number", "width");
        
        stocks.forEach((stockName) => {
            Meteor.call('stock.graph', stockName, function(error, resp) {
                console.log("error", error);
                console.log("resp", resp);

                var index = resp.timestamp.length-1;
                
                const macd = sma(resp.indicators.quote[0].close, index, 12) - sma(resp.indicators.quote[0].close, index, 26);
                const squeeze = bollinger(resp.indicators.quote[0].close, index, 20).high - bollinger(resp.indicators.quote[0].close, index, 20).low;
                data.addRow([stockName, macd, squeeze]);
                console.log('data', data, options);
            });
            //chart.clearChart();
            chart.draw(data, options); 
        });  
        chart.draw(data, options); 
        console.log('chart', chart);
    }

</script>

<div id="chart_div"/>
